import { Lato } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";
import { headers } from "next/headers";
import AppSidebar from "@/components/layout/AppSidebar";
import { Toaster } from "react-hot-toast";
import { Page } from "@/models/Page";
import mongoose from "mongoose";
import { faBars, faShareNodes } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Link from "next/link";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700" ] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppTemplate({ children, ...rest }) {

  // We can observe information we wil nedd
  console.log("Inside rest, we expect:-------", rest);
  console.log("Inside rest, we expect:-------", arguments);
  const headersList = headers();
  console.log("Inside rest, we expect:-------", headersList);
  console.log("---------",headersList.get("host"));
  console.log("+++++++++",headersList.get("referer"));
  console.log("+++++++++",headersList);
  // With this instructions we can see everything we have into headers() of next
  console.log("*********", [...headersList]);
  
  // const url = headersList.get("next-url");
  // console.log("..........", url);

  const session = await getServerSession(authOptions);

  if (!session) {
    return redirect("/");
  }

  mongoose.connect(process.env.MONGODB_URI);
  const page = await Page.findOne({owner: session.user.email});

  return (
    <html lang="en">
      <body className={lato.className}>
        <Toaster />
        <main className="md:flex min-h-screen">
          <label htmlFor="navCb" className="md:hidden ml-8 mt-4 px-4 py-2 rounded-md bg-white shadow inline-flex items-center gap-2 cursor-pointer">
            <FontAwesomeIcon icon={faBars}/>
              <span>Menu - Open Navigation</span>
          </label>
          <input id="navCb" type="checkbox" className="hidden" />
          <label htmlFor="navCb" className="hidden backdrop fixed inset-0 bg-black/70 z-10"></label>
          <aside className="bg-white w-48 p-4 pt-6 shadow fixed md:static -left-48 top-0 bottom-0 z-20 transition-all">
            <div className="sticky top-0 pt-2">
              <div className="rounded-full overflow-hidden aspect-square w-24 mx-auto">
                <Image src={session.user.image} alt={"avatar"} width={256} height={256}/>
              </div>
                {page && (
                  <Link
                    target="_blank"
                    href={"/"+page.uri}
                    className="text-center mt-4 flex gap-1 items-center justify-center"  
                  >
                    <FontAwesomeIcon size="lg" icon={faShareNodes} className="text-blue-500"/>
                    <span className="text-xl text-gray-300">/</span>
                    <span>{page.uri}</span>
                  </Link>
                )}
              <div className="text-center">
                <AppSidebar />
              </div>
            </div>
          </aside>   
          <div className="grow">
              {children}
          </div>         
        </main>
      </body>
    </html>
  );
}
